# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module BreedloveDesign::Papercute::Bridge::Promise::ConsolePlugin; end
module BreedloveDesign::Papercute::Bridge::Utils::AE::ConsolePlugin; end
module Gem::Ext::BuildError; end
